echo Inicio de la escena 1
espeak -v it+f1 "Hola"
echo "Dentro del bloque si de afuera"
echo "Dentro del bloque si del medio"
echo "Condicional - Condicional anidado conseguido!!! :)"
echo "Dentro del bloque si de adentro"
echo "Condicional - Condicional anidado conseguido!!! :)"
espeak -v es-la+m4 -a 30 -s 300 "Hi, Mary. I am John"
sleep 1
espeak -v es-la+m4 -a 30 -s 80 "Hi, Mary. I am John"
sleep 2.5
espeak -v es-la+m4 -a 30 -a 200 "Hi, Mary. I am John"
espeak -v it+f1 "Hola"
espeak -v fr+m3 "Hello"
echo "prueba 1"
echo "prueba 2"
echo "Bucle - Bucle anidado conseguido !!! :)"
echo "Bucle - Condicional anidado conseguido!!! :)"
echo "Bucle - Condicional anidado conseguido!!! :)"
echo "Bucle - Condicional anidado conseguido!!! :)"
echo "Bucle - Condicional anidado conseguido!!! :)"
echo "Bucle - Condicional anidado conseguido!!! :)"
echo "Bucle - Condicional anidado conseguido!!! :)"
echo "Bucle - Condicional anidado conseguido!!! :)"
espeak -v it+f1 "Hola"
espeak -v fr+m3 "Hello"
echo "prueba 1"
echo "prueba 2"
echo "Bucle - Bucle anidado conseguido !!! :)"
echo "Bucle - Condicional anidado conseguido!!! :)"
echo "Bucle - Condicional anidado conseguido!!! :)"
echo "Bucle - Condicional anidado conseguido!!! :)"
echo "Bucle - Condicional anidado conseguido!!! :)"
echo "Bucle - Condicional anidado conseguido!!! :)"
echo "Bucle - Condicional anidado conseguido!!! :)"
echo "Bucle - Condicional anidado conseguido!!! :)"
espeak -v it+f1 "Hola"
espeak -v fr+m3 "Hello"
echo "prueba 1"
echo "prueba 2"
echo "Bucle - Bucle anidado conseguido !!! :)"
echo "Bucle - Condicional anidado conseguido!!! :)"
echo "Bucle - Condicional anidado conseguido!!! :)"
echo "Bucle - Condicional anidado conseguido!!! :)"
echo "Bucle - Condicional anidado conseguido!!! :)"
echo "Bucle - Condicional anidado conseguido!!! :)"
echo "Bucle - Condicional anidado conseguido!!! :)"
echo "Bucle - Condicional anidado conseguido!!! :)"
espeak -v it+f1 "Hola"
espeak -v fr+m3 "Hello"
echo "prueba 1"
echo "prueba 2"
echo "Bucle - Bucle anidado conseguido !!! :)"
echo "Bucle - Condicional anidado conseguido!!! :)"
echo "Bucle - Condicional anidado conseguido!!! :)"
echo "Bucle - Condicional anidado conseguido!!! :)"
echo "Bucle - Condicional anidado conseguido!!! :)"
echo "Bucle - Condicional anidado conseguido!!! :)"
echo "Bucle - Condicional anidado conseguido!!! :)"
echo "Bucle - Condicional anidado conseguido!!! :)"
espeak -v it+f1 "Hola"
espeak -v fr+m3 "Hello"
echo "prueba 1"
echo "prueba 2"
echo "Bucle - Bucle anidado conseguido !!! :)"
echo "Bucle - Condicional anidado conseguido!!! :)"
echo "Bucle - Condicional anidado conseguido!!! :)"
echo "Bucle - Condicional anidado conseguido!!! :)"
echo "Bucle - Condicional anidado conseguido!!! :)"
echo "Bucle - Condicional anidado conseguido!!! :)"
echo "Bucle - Condicional anidado conseguido!!! :)"
echo "Bucle - Condicional anidado conseguido!!! :)"
echo "hola$"
echo "adios@"
sleep 4
sleep 1.5
espeak -v it+f1 "Hola"
echo "Dentro del bloque si de afuera"
echo "Dentro del bloque si del medio"
echo "Condicional - Condicional anidado conseguido!!! :)"
echo "Dentro del bloque si de adentro"
echo "Condicional - Condicional anidado conseguido!!! :)"
espeak -v es-la+m4 -a 30 -s 300 "Hi, Mary. I am John"
sleep 1
espeak -v es-la+m4 -a 30 -s 80 "Hi, Mary. I am John"
sleep 2.5
espeak -v es-la+m4 -a 30 -a 200 "Hi, Mary. I am John"
espeak -v it+f1 "Hola"
espeak -v fr+m3 "Hello"
echo "prueba 1"
echo "prueba 2"
echo "Bucle - Bucle anidado conseguido !!! :)"
echo "Bucle - Condicional anidado conseguido!!! :)"
echo "Bucle - Condicional anidado conseguido!!! :)"
echo "Bucle - Condicional anidado conseguido!!! :)"
echo "Bucle - Condicional anidado conseguido!!! :)"
echo "Bucle - Condicional anidado conseguido!!! :)"
echo "Bucle - Condicional anidado conseguido!!! :)"
echo "Bucle - Condicional anidado conseguido!!! :)"
espeak -v it+f1 "Hola"
espeak -v fr+m3 "Hello"
echo "prueba 1"
echo "prueba 2"
echo "Bucle - Bucle anidado conseguido !!! :)"
echo "Bucle - Condicional anidado conseguido!!! :)"
echo "Bucle - Condicional anidado conseguido!!! :)"
echo "Bucle - Condicional anidado conseguido!!! :)"
echo "Bucle - Condicional anidado conseguido!!! :)"
echo "Bucle - Condicional anidado conseguido!!! :)"
echo "Bucle - Condicional anidado conseguido!!! :)"
echo "Bucle - Condicional anidado conseguido!!! :)"
espeak -v it+f1 "Hola"
espeak -v fr+m3 "Hello"
echo "prueba 1"
echo "prueba 2"
echo "Bucle - Bucle anidado conseguido !!! :)"
echo "Bucle - Condicional anidado conseguido!!! :)"
echo "Bucle - Condicional anidado conseguido!!! :)"
echo "Bucle - Condicional anidado conseguido!!! :)"
echo "Bucle - Condicional anidado conseguido!!! :)"
echo "Bucle - Condicional anidado conseguido!!! :)"
echo "Bucle - Condicional anidado conseguido!!! :)"
echo "Bucle - Condicional anidado conseguido!!! :)"
espeak -v it+f1 "Hola"
espeak -v fr+m3 "Hello"
echo "prueba 1"
echo "prueba 2"
echo "Bucle - Bucle anidado conseguido !!! :)"
echo "Bucle - Condicional anidado conseguido!!! :)"
echo "Bucle - Condicional anidado conseguido!!! :)"
echo "Bucle - Condicional anidado conseguido!!! :)"
echo "Bucle - Condicional anidado conseguido!!! :)"
echo "Bucle - Condicional anidado conseguido!!! :)"
echo "Bucle - Condicional anidado conseguido!!! :)"
echo "Bucle - Condicional anidado conseguido!!! :)"
espeak -v it+f1 "Hola"
espeak -v fr+m3 "Hello"
echo "prueba 1"
echo "prueba 2"
echo "Bucle - Bucle anidado conseguido !!! :)"
echo "Bucle - Condicional anidado conseguido!!! :)"
echo "Bucle - Condicional anidado conseguido!!! :)"
echo "Bucle - Condicional anidado conseguido!!! :)"
echo "Bucle - Condicional anidado conseguido!!! :)"
echo "Bucle - Condicional anidado conseguido!!! :)"
echo "Bucle - Condicional anidado conseguido!!! :)"
echo "Bucle - Condicional anidado conseguido!!! :)"
echo "hola$"
echo "adios@"
sleep 4
sleep 1.5
espeak -v it+f1 "Hola"
echo "Dentro del bloque si de afuera"
echo "Dentro del bloque si del medio"
echo "Condicional - Condicional anidado conseguido!!! :)"
echo "Dentro del bloque si de adentro"
echo "Condicional - Condicional anidado conseguido!!! :)"
espeak -v es-la+m4 -a 30 -s 300 "Hi, Mary. I am John"
sleep 1
espeak -v es-la+m4 -a 30 -s 80 "Hi, Mary. I am John"
sleep 2.5
espeak -v es-la+m4 -a 30 -a 200 "Hi, Mary. I am John"
espeak -v it+f1 "Hola"
espeak -v fr+m3 "Hello"
echo "prueba 1"
echo "prueba 2"
echo "Bucle - Bucle anidado conseguido !!! :)"
echo "Bucle - Condicional anidado conseguido!!! :)"
echo "Bucle - Condicional anidado conseguido!!! :)"
echo "Bucle - Condicional anidado conseguido!!! :)"
echo "Bucle - Condicional anidado conseguido!!! :)"
echo "Bucle - Condicional anidado conseguido!!! :)"
echo "Bucle - Condicional anidado conseguido!!! :)"
echo "Bucle - Condicional anidado conseguido!!! :)"
espeak -v it+f1 "Hola"
espeak -v fr+m3 "Hello"
echo "prueba 1"
echo "prueba 2"
echo "Bucle - Bucle anidado conseguido !!! :)"
echo "Bucle - Condicional anidado conseguido!!! :)"
echo "Bucle - Condicional anidado conseguido!!! :)"
echo "Bucle - Condicional anidado conseguido!!! :)"
echo "Bucle - Condicional anidado conseguido!!! :)"
echo "Bucle - Condicional anidado conseguido!!! :)"
echo "Bucle - Condicional anidado conseguido!!! :)"
echo "Bucle - Condicional anidado conseguido!!! :)"
espeak -v it+f1 "Hola"
espeak -v fr+m3 "Hello"
echo "prueba 1"
echo "prueba 2"
echo "Bucle - Bucle anidado conseguido !!! :)"
echo "Bucle - Condicional anidado conseguido!!! :)"
echo "Bucle - Condicional anidado conseguido!!! :)"
echo "Bucle - Condicional anidado conseguido!!! :)"
echo "Bucle - Condicional anidado conseguido!!! :)"
echo "Bucle - Condicional anidado conseguido!!! :)"
echo "Bucle - Condicional anidado conseguido!!! :)"
echo "Bucle - Condicional anidado conseguido!!! :)"
espeak -v it+f1 "Hola"
espeak -v fr+m3 "Hello"
echo "prueba 1"
echo "prueba 2"
echo "Bucle - Bucle anidado conseguido !!! :)"
echo "Bucle - Condicional anidado conseguido!!! :)"
echo "Bucle - Condicional anidado conseguido!!! :)"
echo "Bucle - Condicional anidado conseguido!!! :)"
echo "Bucle - Condicional anidado conseguido!!! :)"
echo "Bucle - Condicional anidado conseguido!!! :)"
echo "Bucle - Condicional anidado conseguido!!! :)"
echo "Bucle - Condicional anidado conseguido!!! :)"
espeak -v it+f1 "Hola"
espeak -v fr+m3 "Hello"
echo "prueba 1"
echo "prueba 2"
echo "Bucle - Bucle anidado conseguido !!! :)"
echo "Bucle - Condicional anidado conseguido!!! :)"
echo "Bucle - Condicional anidado conseguido!!! :)"
echo "Bucle - Condicional anidado conseguido!!! :)"
echo "Bucle - Condicional anidado conseguido!!! :)"
echo "Bucle - Condicional anidado conseguido!!! :)"
echo "Bucle - Condicional anidado conseguido!!! :)"
echo "Bucle - Condicional anidado conseguido!!! :)"
echo "hola$"
echo "adios@"
sleep 4
sleep 1.5
espeak -v it+f1 "Hola"
echo "Dentro del bloque si de afuera"
echo "Dentro del bloque si del medio"
echo "Condicional - Condicional anidado conseguido!!! :)"
echo "Dentro del bloque si de adentro"
echo "Condicional - Condicional anidado conseguido!!! :)"
espeak -v es-la+m4 -a 30 -s 300 "Hi, Mary. I am John"
sleep 1
espeak -v es-la+m4 -a 30 -s 80 "Hi, Mary. I am John"
sleep 2.5
espeak -v es-la+m4 -a 30 -a 200 "Hi, Mary. I am John"
espeak -v it+f1 "Hola"
espeak -v fr+m3 "Hello"
echo "prueba 1"
echo "prueba 2"
echo "Bucle - Bucle anidado conseguido !!! :)"
echo "Bucle - Condicional anidado conseguido!!! :)"
echo "Bucle - Condicional anidado conseguido!!! :)"
echo "Bucle - Condicional anidado conseguido!!! :)"
echo "Bucle - Condicional anidado conseguido!!! :)"
echo "Bucle - Condicional anidado conseguido!!! :)"
echo "Bucle - Condicional anidado conseguido!!! :)"
echo "Bucle - Condicional anidado conseguido!!! :)"
espeak -v it+f1 "Hola"
espeak -v fr+m3 "Hello"
echo "prueba 1"
echo "prueba 2"
echo "Bucle - Bucle anidado conseguido !!! :)"
echo "Bucle - Condicional anidado conseguido!!! :)"
echo "Bucle - Condicional anidado conseguido!!! :)"
echo "Bucle - Condicional anidado conseguido!!! :)"
echo "Bucle - Condicional anidado conseguido!!! :)"
echo "Bucle - Condicional anidado conseguido!!! :)"
echo "Bucle - Condicional anidado conseguido!!! :)"
echo "Bucle - Condicional anidado conseguido!!! :)"
espeak -v it+f1 "Hola"
espeak -v fr+m3 "Hello"
echo "prueba 1"
echo "prueba 2"
echo "Bucle - Bucle anidado conseguido !!! :)"
echo "Bucle - Condicional anidado conseguido!!! :)"
echo "Bucle - Condicional anidado conseguido!!! :)"
echo "Bucle - Condicional anidado conseguido!!! :)"
echo "Bucle - Condicional anidado conseguido!!! :)"
echo "Bucle - Condicional anidado conseguido!!! :)"
echo "Bucle - Condicional anidado conseguido!!! :)"
echo "Bucle - Condicional anidado conseguido!!! :)"
espeak -v it+f1 "Hola"
espeak -v fr+m3 "Hello"
echo "prueba 1"
echo "prueba 2"
echo "Bucle - Bucle anidado conseguido !!! :)"
echo "Bucle - Condicional anidado conseguido!!! :)"
echo "Bucle - Condicional anidado conseguido!!! :)"
echo "Bucle - Condicional anidado conseguido!!! :)"
echo "Bucle - Condicional anidado conseguido!!! :)"
echo "Bucle - Condicional anidado conseguido!!! :)"
echo "Bucle - Condicional anidado conseguido!!! :)"
echo "Bucle - Condicional anidado conseguido!!! :)"
espeak -v it+f1 "Hola"
espeak -v fr+m3 "Hello"
echo "prueba 1"
echo "prueba 2"
echo "Bucle - Bucle anidado conseguido !!! :)"
echo "Bucle - Condicional anidado conseguido!!! :)"
echo "Bucle - Condicional anidado conseguido!!! :)"
echo "Bucle - Condicional anidado conseguido!!! :)"
echo "Bucle - Condicional anidado conseguido!!! :)"
echo "Bucle - Condicional anidado conseguido!!! :)"
echo "Bucle - Condicional anidado conseguido!!! :)"
echo "Bucle - Condicional anidado conseguido!!! :)"
echo "hola$"
echo "adios@"
sleep 4
sleep 1.5
echo "Condicional - Bucle anidado conseguido!!! :)"
echo "Condicional - Bucle anidado conseguido!!! :)"
echo "Condicional - Bucle anidado conseguido!!! :)"
echo Fin de la escena 1
