echo Inicio de la escena 1
espeak -v fr+m3 "Hello"
espeak -v en+f2 "Hola"
espeak -v en-us+f3 "Hello"
espeak -v en+f2 "Hola"
espeak -v en-us+f3 "Hello"
espeak -v en+f2 "Hola"
espeak -v en-us+f3 "Hello"
espeak -v en+f2 "Hola"
espeak -v en-us+f3 "Hello"
espeak -v it+f1 "Hola"
espeak -v fr+m3 "Hello"
echo "prueba 1"
echo "prueba 2"
espeak -v it+f1 "Hola"
espeak -v fr+m3 "Hello"
echo "prueba 1"
echo "prueba 2"
espeak -v it+f1 "Hola"
espeak -v fr+m3 "Hello"
echo "prueba 1"
echo "prueba 2"
espeak -v it+f1 "Hola"
espeak -v fr+m3 "Hello"
echo "prueba 1"
echo "prueba 2"
espeak -v it+f1 "Hola"
espeak -v fr+m3 "Hello"
echo "prueba 1"
echo "prueba 2"
espeak -v fr+m3 "Hola"
espeak -v it+f1 "Hello"
echo "prueba 1"
echo "prueba 2"
espeak -v fr+m3 "Hola"
espeak -v it+f1 "Hello"
echo "prueba 1"
echo "prueba 2"
espeak -v fr+m3 "Hola"
espeak -v it+f1 "Hello"
echo "prueba 1"
echo "prueba 2"
espeak -v fr+m3 "Hola"
espeak -v it+f1 "Hello"
echo "prueba 1"
echo "prueba 2"
espeak -v fr+m3 "Hola"
espeak -v it+f1 "Hello"
echo "prueba 1"
echo "prueba 2"
echo Fin de la escena 1
