en+f1 "Hello, my name is Mary"
en-us+m2 "Hi, Mary. I am John"
it+f2 "Ciao. Mi chiamo Paola"
en-us+m2 "Ciao, Paola. Il mio nome è John"
es+m1 -s 80 "Escucha la siguiente presentación en inglés"
es+m1 -s 80 "Escucha la siguiente presentación en italiano"
es+m1 -s 80 "Dentro del bloque si de afuera"
es+m1 -s 80 "Dentro del bucle si de adentro"
es+m1 -s 80 "Dentro del bucle si_no de adentro"
es+m1 -s 80 "Dentro del bucle si_no de afuera"
