echo Inicio de la escena 1
espeak -v it+f1 "Hola"
espeak -v fr+m3 "Hello"
echo "prueba 1"
echo "prueba 2"
espeak -v it+f1 "Hola"
espeak -v fr+m3 "Hello"
echo "prueba 1"
echo "prueba 2"
espeak -v it+f1 "Hola"
espeak -v fr+m3 "Hello"
echo "prueba 1"
echo "prueba 2"
espeak -v it+f1 "Hola"
espeak -v fr+m3 "Hello"
echo "prueba 1"
echo "prueba 2"
espeak -v it+f1 "Hola"
espeak -v fr+m3 "Hello"
echo "prueba 1"
echo "prueba 2"
espeak -v it+f1 "Hola"
espeak -v fr+m3 "Hello"
echo "prueba 1"
echo "prueba 2"
espeak -v it+f1 "Hola"
espeak -v fr+m3 "Hello"
echo "prueba 1"
echo "prueba 2"
espeak -v it+f1 "Hola"
espeak -v fr+m3 "Hello"
echo "prueba 1"
echo "prueba 2"
espeak -v it+f1 "Hola"
espeak -v fr+m3 "Hello"
echo "prueba 1"
echo "prueba 2"
espeak -v it+f1 "Hola"
espeak -v fr+m3 "Hello"
echo "prueba 1"
echo "prueba 2"
echo Fin de la escena 1
