espeak -v en+f1 Hello, my name is Mary"
espeak -v en-us+m2 Hi, Mary. I am John"
espeak -v it+f2 Ciao. Mi chiamo Paola"
espeak -v en-us+m2 Ciao, Paola. Il mio nome è John"
espeak -v es+m1 -s 80 Escucha la siguiente presentación en inglés"
espeak -v es+m1 -s 80 Escucha la siguiente presentación en italiano"
espeak -v es+m1 -s 80 Dentro del bloque si de afuera"
espeak -v es+m1 -s 80 Dentro del bucle si de adentro"
espeak -v es+m1 -s 80 Dentro del bucle si_no de adentro"
espeak -v es+m1 -s 80 Dentro del bucle si_no de afuera"
